# Agent config

# Session
IDLE_TIMEOUT = 30.0
TOOL_TIMEOUT = 30.0

# Memory
WORKING_MEMORY_MAX_TOKENS = 8000
EPISODIC_MEMORY_MAX_ENTRIES = 200
SEMANTIC_RETRIEVE_TOP_K = 5
CONSOLIDATE_INTERVAL = 10
IMPORTANCE_PRUNE_AGE = 3600
IMPORTANCE_PRUNE_THRESHOLD = 0.3

# Context
CONTEXT_TOKEN_BUDGET = 4096
RECENT_TURNS = 3
RECENT_EVENTS = 10

# Observation
DEFAULT_MAX_HEALTH = 20
DEFAULT_MAX_FOOD = 20

# LLM
LLM_MAX_TOKENS = 1024
LLM_PROXY_URL = "http://localhost:4000"

# Network
ORCHESTRATOR_PORT = 8000
WEBSOCKET_PING_TIMEOUT = 60
WEBSOCKET_PING_INTERVAL = 30
OBSERVATION_TIMEOUT = 10.0
RECONNECT_DELAY = 5.0
LLM_ERROR_BACKOFF = 5.0

# Importance
CHAT_EVENT_IMPORTANCE = 2.0
ACTION_COMPLETED_IMPORTANCE = 2.5
ACTION_FAILED_IMPORTANCE = 3.0
NARRATOR_EVENT_IMPORTANCE = 3.0

# Narrator
NARRATOR_TOKEN_BUDGET = 2048
NARRATOR_INTERVAL = 20

# CLI
DEFAULT_BOTS = 2
DEFAULT_MC_PORT = 25565
DEFAULT_RCON_PORT = 25575
DEFAULT_RCON_PASSWORD = "password"
